<html lang="pl-PL">

<#include "header.ftlh"/>
<main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">

<head>
       <meta charset="UTF-8" />
    <title>Zajavka-crypto_analyzer</title>
<style>
    body{
        background-image: url("bg-info.jpg");
        background-position: center;
        background-repeat: no-repeat;
        background-size: cover;
    }
.names{
    font-size: 30px;
    font-family: Monospaced;
    color: whitesmoke;
    margin-top: 350px;
    width: 300px;
    float: right;
}
    h1{
        color: whitesmoke;
        margin-top: 200px;
        width: 300px;
        float: right;
    }

</style>

</head>

<body>

<h1>ZAJAVKA</h1>

<div class="names">

<p lang="pl">${member1}</p>
<p lang="pl">${member2}</p>
<p lang="pl">${member3}</p>
<p lang="pl">${member4}</p>

</div>

<body>

<#--</main>-->
<#--<#include "footer.ftlh"/>-->
</html>